### ISSUE TITLE
Login Bind Warning

### ISSUE THREAD

**Issue by c-tsoi** [pcdshub/shared-dotfiles#41]
When I log in to pslogin I get the following warning:
/cds/home/c/ctsoi/dotfiles/on_site/bashrc: line 102: bind: warning: line editing not enabled
/cds/home/c/ctsoi/dotfiles/on_site/bashrc: line 105: bind: warning: line editing not enabled
/cds/home/c/ctsoi/dotfiles/on_site/bashrc: line 108: bind: warning: line editing not enabled
/cds/home/c/ctsoi/dotfiles/on_site/bashrc: line 111: bind: warning: line editing not enabled
/cds/home/c/ctsoi/dotfiles/on_site/bashrc: line 278: bind: warning: line editing not enabled

**Comment by ZLLentz** [comment]
Some googling seems to indicate that this happens when a script tries to call `bind` but it's not in a login shell.
https://superuser.com/questions/240223/warning-line-editing-not-enabled
In what way are you logging into pslogin? I think we can use some of the tips in that linked thread to resolve this

**Comment by c-tsoi** [comment]
I will try adding that line to the bashrc and see if it fixes the problem. To answer your question, I use the psbuild-rhel7 shortcut from the offsite mode in the shared dot files that Ken demoed.

**Comment by klauer** [comment]
@c-tsoi uses the `source $HOME/dotfiles/on_site/bash_all.sh` method at the end of `~/.bashrc`. There's a spot in the normal on-site `bashrc` where it checks for a login shell, but this is skipped over with this alternative method.

I think we might want to just add a guard in `bash_all.sh` to say "if not a login shell; skip sourcing"

**Comment by c-tsoi** [comment]
Sorry, I am a bit of a novice with this kind of thing. Is this something I have to do myself or can I copy someone else's edits?
